### ISSUE TITLE
API to convert UINT8Array of PDF to image buffer

### ISSUE THREAD

**Issue by vazgen6** [olliet88/pdf-img-convert.js#2]
I was wondering if it's possible to have the option mentioned in the title to convert UINT8Array of PDF to image buffer. Instead of reading the PDF from a file like this `convert('http://www.example.com/pdf_online.pdf');  we just do maybe something like this
```
const imageBuffer = convert(uint8Array);
```

**Comment by olliet88** [comment]
This has now been implemented in version 1.0.3 - just update with npm 🙂
