### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by AgustLuj** [olliet88/pdf-img-convert.js#9]
hi, when I convert the pdf in the console I get multiple alerts that say something like this
  Warning: getPathGenerator - ignoring character: "Error: Requesting object that isn't resolved yet TrebuchetMS_path_1.".
maybe more 10

**Comment by olliet88** [comment]
Hi, this is caused by the current issue #3  - you'll find that the characters mentioned in the warnings show up weirdly on the resulting image. I haven't been able to find a solution to this yet.
